_commit: 1.6.1
_src_path: gh:natir/copier-rust
author_email: pierre@marijon.fr
author_name: Pierre Marijon
ci: github
cli: true
copyright_date: '2023'
copyright_holder: Pierre Marijon
copyright_holder_email: pierre@marijon.fr
copyright_license: MIT
forge_host: github.com
forge_host_custom: null
forge_namespace: natir
forge_repo_name: pcon
msrv: '1.65'
project_description: Prompt COuNter, a short kmer counter.
project_name: pcon
