[package]
name = "pcon"
description = "pcon for Prompt COuNter, is a short kmer counter"
version = "0.1.0"
authors = ["Pierre Marijon <pierre@marijon.fr>"]
edition = "2018"
# build = "build.rs"


[lib]
name = "pcon"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "pcon"
path = "src/main.rs"

[dependencies]
bio             = "0.29"
csv             = "1.1.1"
clap            = "2.33"
bv             = "0.11.0"
cocktail        = {git = "https://github.com/natir/cocktail.git"}

[build-dependencies]
cbindgen	= "0.9.1"


[profile.release]
debug = true # uncomment for proffiling
lto = 'thin'
opt-level = 3
overflow-checks = false
panic = 'abort'
incremental = false