[package]
name = "pcon"
description = "pcon for Prompt COuNter, is a short kmer counter"
version = "0.1.0"
authors = ["Pierre Marijon <pierre@marijon.fr>"]
edition = "2021"
rust-verison = "1.56"

[lib]
name = "pcon"
crate-type = ["rlib", "cdylib", "staticlib"]


[[bin]]
name = "pcon"
path = "src/main.rs"

[dependencies]
noodles         = { version = "0.18", features = ["fasta"] }
cocktail        = { git = "https://github.com/natir/cocktail.git" }

# parallel
rayon           = "1"

# serialization
bitvec		= "1"
byteorder       = "1"

# input output management
term_size      = "0.3"
niffler	       = { version = "2", features = ["bz2", "lzma", "gz"] }
flate2         = "1"

# CLI management
clap           = { version = "3", features = ["derive"] }

# Logging and error management
log 	       = "0.4"
anyhow         = "1"
thiserror      = "1"
env_logger     = "0.9"


[dev-dependencies]
lazy_static	= "1"


[profile.release]
# debug = true ## Uncomment for profile
lto = 'thin'
opt-level = 3
overflow-checks = false
panic = 'abort'
incremental = false
